# Workflow triggered by Gearset standard webhook payload
name: executeBatch

on:
  # Triggered when Gearset sends a standard payload webhook
  repository_dispatch:
    types: [run_my_bat]
  # Optional: allows manual run from Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      # Print the Gearset payload to logs (for debug)
      - name: Show Gearset webhook payload
        run: echo "Received payload from Gearset."

      # Access the payload JSON data (optional advanced use)
      - name: Display event data
        run: echo "${{ toJson(github.event) }}"

      # Your custom command or logic after deployment
      - name: Run a one-line script
        run: echo "Gearset deployment succeeded — running executeBatch workflow."
